(() => {
  'use strict';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const cash=v=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(v||0));
  const cfg=window.SIASCLOUD_CONFIG||{},requestedSlug=new URLSearchParams(location.search).get('tienda')||cfg.storeSlug||'';
  const state={store:null,products:[],cart:[],category:'',sending:false};
  function toast(s){$('#storeToast').textContent=s;$('#storeToast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#storeToast').classList.remove('show'),3000);}
  async function api(action,p={}){const base=String(cfg.functionsBaseUrl||'').replace(/\/$/,'');if(!base)throw new Error('La conexión de la tienda no está configurada');const r=await fetch(`${base}/${cfg.storeFunction||'siascloud-erp'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope:"store",action,payload:{slug:state.store?.slug||requestedSlug,...p}}),cache:'no-store'});let data;try{data=await r.json();}catch{throw new Error('No fue posible conectar con la tienda');}if(!r.ok||!data.ok)throw new Error(data.code==='TIENDA_NO_DISPONIBLE'?'La tienda no está publicada. Su administrador puede activarla desde SiasCloud.':data.code==='ENLACE_TIENDA_REQUERIDO'?'Abre el enlace de la tienda que te entregó la empresa.':data.message||'No fue posible completar la solicitud');return data;}
  const product=id=>state.products.find(p=>p.id===id),cartKey=()=>`sias_cart:${state.store.slug}`;
  function saveCart(){localStorage.setItem(cartKey(),JSON.stringify(state.cart));updateCount();}
  function updateCount(){$('#cartCount').textContent=state.cart.reduce((s,x)=>s+x.quantity,0);}
  function cartTotal(){return state.cart.reduce((s,x)=>s+(product(x.product_id)?.price||0)*x.quantity,0);}
  function add(id,quantity=1){if(!state.store?.allow_orders){toast('Consulta con la tienda para realizar tu pedido');return;}const p=product(id);if(!p||!Number.isFinite(quantity)||quantity<=0||quantity>10000)return;const x=state.cart.find(x=>x.product_id===id);if(x)x.quantity=Math.min(10000,x.quantity+quantity);else state.cart.push({product_id:id,quantity});saveCart();toast(`${p.name} agregado al carrito`);}
  function renderCatalog(){
    const q=$('#catalogSearch').value.trim().toLowerCase(),sort=$('#catalogSort').value;
    const rows=state.products.filter(p=>(!state.category||p.category===state.category)&&(!q||[p.name,p.sku,p.category,p.description].some(v=>String(v||'').toLowerCase().includes(q))));
    rows.sort(sort==='price-asc'?(a,b)=>Number(a.price)-Number(b.price):sort==='price-desc'?(a,b)=>Number(b.price)-Number(a.price):sort==='name'?(a,b)=>a.name.localeCompare(b.name,'es'):(a,b)=>Number(b.featured)-Number(a.featured)||a.name.localeCompare(b.name,'es'));
    $('#catalogCount').textContent=`${rows.length} ${rows.length===1?'producto':'productos'}`;
    $('#productGrid').innerHTML=rows.map(p=>`<article class="product-card"><button class="product-photo" type="button" data-product="${p.id}" aria-label="Ver ${E(p.name)}">${p.image_url?`<img src="${E(p.image_url)}" alt="${E(p.name)}" loading="lazy">`:'<span class="product-placeholder" aria-hidden="true">◇</span>'}${p.featured?'<span class="featured-tag">★ Destacado</span>':''}</button><div class="product-body"><span class="product-category">${E(p.category||'Nuestro catálogo')}</span><h3 class="product-title"><button type="button" data-product="${p.id}">${E(p.name)}</button></h3><div class="product-price">${cash(p.price)}</div><span class="product-unit">por ${E(p.unit||'unidad')} · ${p.exempt?'Exento de IVA':'IVA incluido'}</span><div class="product-stock ${p.available?'':'consult'}">${p.available?(state.store.show_stock?`${Number(p.stock).toLocaleString('es-CL')} disponibles`:'Disponible'):'Consultar disponibilidad'}</div>${state.store.allow_orders?`<button class="add-product" type="button" data-add="${p.id}">+ Agregar al carrito</button>`:`<button class="add-product" type="button" data-product="${p.id}">Ver producto</button>`}</div></article>`).join('')||'<div class="catalog-empty">No hay productos para esta búsqueda.</div>';
    $$('[data-product]').forEach(b=>b.addEventListener('click',()=>details(b.dataset.product)));$$('[data-add]').forEach(b=>b.addEventListener('click',()=>add(b.dataset.add)));
    $$('#productGrid img').forEach(img=>img.addEventListener('error',()=>{img.replaceWith(Object.assign(document.createElement('span'),{className:'product-placeholder',textContent:'◇'}));}));
  }
  function details(id){const p=product(id);if(!p)return;$('#productDetail').innerHTML=`<div class="product-detail-grid"><div class="product-detail-photo">${p.image_url?`<img src="${E(p.image_url)}" alt="${E(p.name)}">`:'<span class="product-placeholder">◇</span>'}</div><div class="product-detail-copy"><span class="eyebrow">${E(p.category||'PRODUCTO')}</span><h2>${E(p.name)}</h2><p>${E(p.description||'Consulta con nuestro equipo si necesitas más información sobre este producto.')}</p><div class="detail-price">${cash(p.price)}</div><small class="muted">por ${E(p.unit||'unidad')} · ${p.exempt?'Exento de IVA':'IVA incluido'}</small>${state.store.allow_orders?'<label class="detail-quantity">Cantidad<input id="detailQuantity" type="number" min="1" max="10000" step="1" value="1"></label><button id="detailAdd" class="button primary full-button" type="button">Agregar al carrito</button>':''}</div></div>`;$('#productDialog').showModal();$('#detailAdd')?.addEventListener('click',()=>{const qty=Number($('#detailQuantity').value);if(!Number.isInteger(qty)||qty<1||qty>10000){toast('Ingresa una cantidad válida');return;}add(id,qty);$('#productDialog').close();});}
  function renderCart(){
    state.cart=state.cart.filter(x=>product(x.product_id));saveCart();
    $('#cartItems').innerHTML=state.cart.map(x=>{const p=product(x.product_id);return `<div class="cart-row">${p.image_url?`<img src="${E(p.image_url)}" alt="">`:'<div class="cart-mini-placeholder"></div>'}<div><strong>${E(p.name)}</strong><small>${cash(p.price)} por ${E(p.unit)}</small></div><input type="number" min="1" max="10000" step="1" value="${x.quantity}" data-cart-qty="${p.id}" aria-label="Cantidad de ${E(p.name)}"><strong class="cart-line-total">${cash(p.price*x.quantity)}</strong><button class="remove-cart" type="button" data-cart-remove="${p.id}" aria-label="Quitar ${E(p.name)}">×</button></div>`;}).join('')||'<div class="cart-empty">Tu carrito está vacío. Explora el catálogo y agrega tus favoritos.</div>';
    $('#cartSummary').innerHTML=state.cart.length?`<div class="cart-total"><span>Total de productos</span><strong>${cash(cartTotal())}</strong></div><button class="button primary full-button" id="goCheckout" type="button">Continuar con la solicitud</button><p class="order-explanation">El pedido y el despacho serán confirmados por nuestro equipo.</p>`:'';
    $$('[data-cart-remove]').forEach(b=>b.addEventListener('click',()=>{state.cart=state.cart.filter(x=>x.product_id!==b.dataset.cartRemove);renderCart();}));
    $$('[data-cart-qty]').forEach(input=>input.addEventListener('change',()=>{const qty=Number(input.value);if(!Number.isInteger(qty)||qty<1||qty>10000){renderCart();return;}state.cart.find(x=>x.product_id===input.dataset.cartQty).quantity=qty;renderCart();}));
    $('#goCheckout')?.addEventListener('click',()=>{$('#cartDialog').close();$('#checkoutTotal').textContent=cash(cartTotal());$('#checkoutError').textContent='';$('#checkoutDialog').showModal();});
  }
  async function load(){
    $('#storeLoading').classList.remove('hidden');$('#storeError').classList.add('hidden');$('#storeContent').classList.add('hidden');
    try{const r=await api('catalog');state.store=r.store;state.products=r.rows||[];const s=state.store;
      document.title=`${s.title} · Tienda`;document.documentElement.style.setProperty('--store-primary',/^#[a-f0-9]{6}$/i.test(s.primary_color)?s.primary_color:'#2563eb');
      for(const [id,value] of [['#storeName',s.title],['#storeFooterName',s.title],['#storeTagline',s.tagline||'Bienvenido a nuestra tienda'],['#storeHeroTitle',s.hero_title||'Productos para cada día'],['#storeHeroText',s.hero_text||'Explora nuestro catálogo y envía tu solicitud de pedido.'],['#storeAboutTitle',s.about_title||'Estamos para ayudarte'],['#storeAboutText',s.about_text||'Encuentra tus productos favoritos y coordina tu pedido con nuestro equipo.'],['#storeDeliveryText',s.delivery_text||'Coordina la entrega o retiro con nuestro equipo al confirmar tu pedido.'],['#storeFooterAddress',s.contact_address||''],['#storeTerms',s.terms||'Las solicitudes están sujetas a confirmación de disponibilidad, entrega y pago. Los datos ingresados se utilizan para atender y gestionar tu solicitud.']])$(id).textContent=value;
      if(s.logo_url)$('#storeLogo').src=s.logo_url;
      if(s.hero_image)$('#storeHeroMedia').innerHTML=`<img src="${E(s.hero_image)}" alt="${E(s.title)}">`;
      $('#storeContactLinks').innerHTML=`${s.whatsapp&&/^\d{8,15}$/.test(s.whatsapp)?`<a href="https://wa.me/${s.whatsapp}" target="_blank" rel="noopener">Contactar por WhatsApp ↗</a>`:''}${s.contact_email&&/^\S+@\S+\.\S+$/.test(s.contact_email)?`<a href="mailto:${E(s.contact_email)}">${E(s.contact_email)}</a>`:''}`;
      try{const data=JSON.parse(localStorage.getItem(cartKey())||'[]');state.cart=Array.isArray(data)?data.filter(x=>product(x.product_id)&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=10000).slice(0,60):[];}catch{state.cart=[];}
      const categories=[...new Set(state.products.map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));$('#catalogCategories').innerHTML=`<button type="button" class="active" data-category="">Todos</button>${categories.map(c=>`<button type="button" data-category="${E(c)}">${E(c)}</button>`).join('')}`;
      $$('[data-category]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;$$('[data-category]').forEach(x=>x.classList.toggle('active',x===b));renderCatalog();}));
      $('#openCart').disabled=!s.allow_orders;saveCart();renderCatalog();$('#storeContent').classList.remove('hidden');
    }catch(err){$('#storeErrorText').textContent=err.message;$('#storeError').classList.remove('hidden');}finally{$('#storeLoading').classList.add('hidden');}
  }
  $('#catalogSearch').addEventListener('input',renderCatalog);$('#catalogSort').addEventListener('change',renderCatalog);$('#storeRetry').addEventListener('click',load);
  $('#openCart').addEventListener('click',()=>{if(!state.store)return;renderCart();$('#cartDialog').showModal();});
  $$('[data-close]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.close==='checkoutDialog'&&state.sending)return;$('#'+b.dataset.close).close();}));
  $$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom){if(d.id==='checkoutDialog'&&state.sending)return;d.close();}}));
  $('#openTerms').addEventListener('click',()=>{if(state.store)$('#termsDialog').showModal();});
  $('#checkoutDelivery').addEventListener('change',()=>{const required=$('#checkoutDelivery').value==='DESPACHO';$$('.delivery-address').forEach(label=>{label.classList.toggle('hidden',!required);label.querySelector('input').required=required;});});
  $('#checkoutDialog').addEventListener('cancel',e=>{if(state.sending)e.preventDefault();});
  $('#checkoutForm').addEventListener('submit',async e=>{
    e.preventDefault();const form=e.currentTarget;if(state.sending||!state.cart.length)return;state.sending=true;$('#submitOrder').disabled=true;$('#submitOrder').textContent='Enviando solicitud…';$('#checkoutError').textContent='';
    try{const fd=new FormData(form),contact=Object.fromEntries([...fd].filter(([k])=>!['accept_terms','website'].includes(k))),payload={contact,items:state.cart.map(x=>({...x})),website:fd.get('website'),accept_terms:fd.get('accept_terms')==='on'};
      const bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(payload)))),fingerprint=[...bytes].map(x=>x.toString(16).padStart(2,'0')).join(''),pendingKey=`sias_pending:${state.store.slug}`;
      let pending;try{pending=JSON.parse(sessionStorage.getItem(pendingKey)||'null');}catch{}
      if(!pending||pending.fingerprint!==fingerprint){pending={request_key:crypto.randomUUID(),fingerprint};sessionStorage.setItem(pendingKey,JSON.stringify(pending));}
      const r=await api('orders.create',{...payload,request_key:pending.request_key});
      state.cart=[];saveCart();sessionStorage.removeItem(pendingKey);$('#checkoutDialog').close();$('#successNumber').textContent=r.number;$('#successTotal').textContent=r.total!==undefined?`Total registrado: ${cash(r.total)}`:'';$('#successDialog').showModal();form.reset();$$('.delivery-address').forEach(label=>{label.classList.add('hidden');label.querySelector('input').required=false;});
    }catch(err){$('#checkoutError').textContent=err.message;}finally{state.sending=false;$('#submitOrder').disabled=false;$('#submitOrder').textContent='Enviar solicitud';}
  });
  $('#storeYear').textContent=new Date().getFullYear();load();
})();
